configured_endpoints: 41
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/plastic-labs%2Fhoncho-cd104b525abaef677f606c54563ea351cf16a0874b0d0edb18f85cc877747d48.yml
openapi_spec_hash: 7ceb6ba4a3badc885acee47872cb170f
config_hash: d1af3adc0f176eada1fd7fb38e8bc405
