configured_endpoints: 32
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/plastic-labs%2Fhoncho-97e45ec65d0b4245b757ba17cbe7a42a96fcb617a2e0aaa3cf8afb7c91f94488.yml
openapi_spec_hash: 1ee11ef5c85758dd48af6b5bdd8ec8d6
config_hash: 6e7613b005bb1ff57a0daa84b8acafd9
