configured_endpoints: 31
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/plastic-labs%2Fhoncho-a5cd3a1347f8d95aea9b8f8206c6b226abb9c20e7d0d99b1fa1896ee949b0d33.yml
openapi_spec_hash: 5319633fba1bdcf4aa0b9c0aaa086a1d
config_hash: 5ca738ccfa5fd2fbd48e97ed0226ad78
